#!/bin/bash

# Azure Custom Domain Validation - DNS Fix Script
# Run this on your DNS provider (e.g., Hostinger, Cloudflare, etc.)

echo "🔧 Azure Custom Domain DNS Fix Script"
echo "====================================="
echo "Domain: prepbettr.com"
echo "Azure SWA: prepbettr-swa"
echo "Validation Token: _sublkgv7ispv97e1i2cqtzq3i3jz7ge"
echo ""

echo "📋 REQUIRED DNS CHANGES:"
echo ""

echo "1. 🚨 CRITICAL: Fix CAA Record (BLOCKING SSL)"
echo "   Current CAA: 0 issue \"letsencrypt.org\""
echo "   Action: REMOVE or REPLACE this CAA record"
echo ""
echo "   Option A (Recommended): Remove CAA record entirely"
echo "   Option B: Replace with multiple CA support:"
echo "   prepbettr.com CAA 0 issue \"letsencrypt.org\""
echo "   prepbettr.com CAA 0 issue \"digicert.com\""
echo "   prepbettr.com CAA 0 issue \"pki.goog\""
echo ""

echo "2. ✅ ADD: DNS Authentication Record"
echo "   Name: _dnsauth.prepbettr.com"
echo "   Type: TXT"
echo "   Value: _sublkgv7ispv97e1i2cqtzq3i3jz7ge"
echo "   TTL: 300 (5 minutes)"
echo ""

echo "3. ✅ VERIFY: A Record (CORRECT)"
echo "   Name: prepbettr.com (or @)"
echo "   Type: A"
echo "   Value: 168.63.140.18"
echo "   TTL: 300 (5 minutes)"
echo "   Status: ✅ Already correct"
echo ""

echo "4. ✅ KEEP: Current TXT Records"
echo "   prepbettr.com TXT \"v=spf1include:_spf.mail.hostinger.com~all\""
echo "   prepbettr.com TXT \"_sublkgv7ispv97e1i2cqtzq3i3jz7ge\""
echo "   Status: ✅ Keep both records"
echo ""

echo "📝 DNS PROVIDER INSTRUCTIONS:"
echo ""
echo "If using Hostinger:"
echo "1. Log into Hostinger control panel"
echo "2. Go to Domain → Manage → DNS Zone"
echo "3. Find CAA record and DELETE it"
echo "4. ADD new TXT record: _dnsauth.prepbettr.com → _sublkgv7ispv97e1i2cqtzq3i3jz7ge"
echo "5. Save changes"
echo ""

echo "If using Cloudflare:"
echo "1. Log into Cloudflare dashboard" 
echo "2. Select prepbettr.com domain"
echo "3. Go to DNS → Records"
echo "4. Find CAA record and DELETE it"
echo "5. ADD new TXT record: _dnsauth → _sublkgv7ispv97e1i2cqtzq3i3jz7ge"
echo "6. Save changes"
echo ""

echo "⏱️  VERIFICATION COMMANDS:"
echo ""
echo "# Wait 5-15 minutes after DNS changes, then run:"
echo "dig prepbettr.com CAA +short                    # Should be empty or allow multiple CAs"
echo "dig _dnsauth.prepbettr.com TXT +short           # Should return: \"_sublkgv7ispv97e1i2cqtzq3i3jz7ge\""
echo "dig prepbettr.com A +short                      # Should return: 168.63.140.18"
echo ""

echo "🔄 AZURE RESET PROCEDURE:"
echo ""
echo "After DNS changes propagate (15-30 min), run:"
echo "1. az staticwebapp hostname delete --name prepbettr-swa --resource-group PrepBettr_group --hostname prepbettr.com"
echo "2. Wait 10 minutes"
echo "3. az staticwebapp hostname add --name prepbettr-swa --resource-group PrepBettr_group --hostname prepbettr.com"
echo "4. Monitor: az staticwebapp hostname list --name prepbettr-swa --resource-group PrepBettr_group"
echo ""

echo "🎯 EXPECTED TIMELINE:"
echo "• DNS propagation: 5-15 minutes"
echo "• Azure validation: 5-30 minutes"  
echo "• SSL certificate: 5-60 minutes"
echo "• Total: 15-105 minutes"
echo ""

echo "✅ SUCCESS INDICATORS:"
echo "• Azure hostname status: 'Validating' → 'Configured'"
echo "• HTTPS works: curl -I https://prepbettr.com"
echo "• SSL certificate issued by Microsoft/DigiCert"
echo ""

echo "❌ If validation still fails after DNS fixes:"
echo "• Check Firebase console for custom domains"
echo "• Verify no other hosting service claims prepbettr.com"
echo "• Contact Azure support with this error log"
echo ""

echo "📞 Support Information:"
echo "• Azure Static Web Apps: prepbettr-swa"
echo "• Resource Group: PrepBettr_group"
echo "• Subscription: Azure subscription 1"
echo "• GitHub Workflow: jolly-cliff-0244e530f"
