/**
 * MAINTENANCE NOTE: Static Icon Import Module
 * 
 * This file contains all tech icons imported statically to satisfy Next.js optimization requirements.
 * Next.js tree-shaking can drop icons when using dynamic imports or barrel exports from icon libraries.
 * 
 * IMPORTANT: When adding new tech icons:
 * 1. Import the icon explicitly in the relevant import block (FontAwesome or Simple Icons)
 * 2. Add the icon to the techIconMap object below
 * 3. DO NOT use dynamic access patterns like `react-icons/fa[iconName]`
 * 4. Test that the new icon renders correctly in production builds
 * 
 * This approach ensures all icons are bundled properly and available at runtime.
 */

// Dedicated static import module for tech icons
// Each icon is explicitly imported to prevent Next.js barrel optimization from dropping them

// FontAwesome Icons
import {
  FaReact,
  FaVuejs,
  FaAngular,
  FaHtml5,
  FaCss3Alt,
  FaSass,
  FaBootstrap,
  FaNodeJs,
  FaPython,
  FaJava,
  FaPhp,
  FaDocker,
  FaAws,
  FaGitAlt,
  FaGithub,
  FaGitlab,
  FaBitbucket,
  FaWordpress,
  FaDrupal,
  FaJoomla,
  FaApple,
  FaAndroid,
} from 'react-icons/fa';

// Simple Icons
import {
  SiNextdotjs,
  SiSvelte,
  SiTypescript,
  SiJavascript,
  SiTailwindcss,
  SiMui,
  SiExpress,
  SiDjango,
  SiFlask,
  SiSpring,
  SiRuby,
  SiRubyonrails,
  SiGo,
  SiRust,
  SiDotnet,
  SiMongodb,
  SiMysql,
  SiPostgresql,
  SiRedis,
  SiSqlite,
  SiOracle,
  SiElasticsearch,
  SiFlutter,
  SiSwift,
  SiKotlin,
  SiKubernetes,
  SiGooglecloud,
  SiFirebase,
  SiVercel,
  SiNetlify,
  SiWebpack,
  SiVite,
  SiRollupdotjs,
  SiBabel,
  SiEslint,
  SiPrettier,
  SiJest,
  SiCypress,
  SiRedux,
  SiMobx,
  SiGraphql,
  SiApollographql,
  SiPostman,
  SiJenkins,
  SiGithubactions,
  SiCircleci,
  SiTravisci,
  SiLaravel,
  SiSymfony,
  SiCodeigniter,
  SiShopify,
  SiStrapi,
  SiContentful,
  SiSanity,
  SiNuxtdotjs,
  SiGatsby,
  SiBackbonedotjs,
  SiPoly,
  SiAstro,
  SiFastapi,
  SiNestjs,
  SiKoa,
  SiHp,
  SiStripe,
  SiDeno,
  SiSupabase,
  SiPrisma,
  SiSequelize,
  SiMariadb,
  SiNeo4J,
  SiInfluxdb,
  SiGrafana,
  SiPrometheus,
  SiTerraform,
  SiAnsible,
  SiPuppet,
  SiHelm,
  SiArgo,
  SiRancher,
  SiDatadog,
  SiNewrelic,
  SiSentry,
  SiElastic,
  SiLogstash,
  SiKibana,
  SiApachekafka,
  SiRabbitmq,
  SiApachespark,
  SiDatabricks,
  SiSnowflake,
  SiTableau,
  SiPowers,
  SiQlik,
  SiD3Dotjs,
  SiChartdotjs,
  SiPlotly,
  SiLeaflet,
  SiMapbox,
  SiThreedotjs,
  SiSelenium,
  SiTestinglibrary,
  SiVitest,
  SiStorybook,
  SiChromatic,
  SiZod,
  SiPyup,
  SiFigma,
  SiSketch,
  SiAdobexd,
  SiFramer,
  SiSolidity,
  SiEthereum,
  SiWeb3Dotjs,
  SiIpfs,
  SiChainlink,
  SiAlchemy,
} from 'react-icons/si';

// Tech icon mapping with explicit imports
export const techIconMap = {
  // FontAwesome Icons
  FaReact,
  FaVuejs,
  FaAngular,
  FaHtml5,
  FaCss3Alt,
  FaSass,
  FaBootstrap,
  FaNodeJs,
  FaPython,
  FaJava,
  FaPhp,
  FaDocker,
  FaAws,
  FaGitAlt,
  FaGithub,
  FaGitlab,
  FaBitbucket,
  FaWordpress,
  FaDrupal,
  FaJoomla,
  FaApple,
  FaAndroid,

  // Simple Icons
  SiNextdotjs,
  SiSvelte,
  SiTypescript,
  SiJavascript,
  SiTailwindcss,
  SiMui,
  SiExpress,
  SiDjango,
  SiFlask,
  SiSpring,
  SiRuby,
  SiRubyonrails,
  SiGo,
  SiRust,
  SiDotnet,
  SiMongodb,
  SiMysql,
  SiPostgresql,
  SiRedis,
  SiSqlite,
  SiOracle,
  SiElasticsearch,
  SiFlutter,
  SiSwift,
  SiKotlin,
  SiKubernetes,
  SiGooglecloud,
  SiFirebase,
  SiVercel,
  SiNetlify,
  SiWebpack,
  SiVite,
  SiRollupdotjs,
  SiBabel,
  SiEslint,
  SiPrettier,
  SiJest,
  SiCypress,
  SiRedux,
  SiMobx,
  SiGraphql,
  SiApollographql,
  SiPostman,
  SiJenkins,
  SiGithubactions,
  SiCircleci,
  SiTravisci,
  SiLaravel,
  SiSymfony,
  SiCodeigniter,
  SiShopify,
  SiStrapi,
  SiContentful,
  SiSanity,
  SiNuxtdotjs,
  SiGatsby,
  SiBackbonedotjs,
  SiPoly,
  SiAstro,
  SiFastapi,
  SiNestjs,
  SiKoa,
  SiHp,
  SiStripe,
  SiDeno,
  SiSupabase,
  SiPrisma,
  SiSequelize,
  SiMariadb,
  SiNeo4J,
  SiInfluxdb,
  SiGrafana,
  SiPrometheus,
  SiTerraform,
  SiAnsible,
  SiPuppet,
  SiHelm,
  SiArgo,
  SiRancher,
  SiDatadog,
  SiNewrelic,
  SiSentry,
  SiElastic,
  SiLogstash,
  SiKibana,
  SiApachekafka,
  SiRabbitmq,
  SiApachespark,
  SiDatabricks,
  SiSnowflake,
  SiTableau,
  SiPowers,
  SiQlik,
  SiD3Dotjs,
  SiChartdotjs,
  SiPlotly,
  SiLeaflet,
  SiMapbox,
  SiThreedotjs,
  SiSelenium,
  SiTestinglibrary,
  SiVitest,
  SiStorybook,
  SiChromatic,
  SiZod,
  SiPyup,
  SiFigma,
  SiSketch,
  SiAdobexd,
  SiFramer,
  SiSolidity,
  SiEthereum,
  SiWeb3Dotjs,
  SiIpfs,
  SiChainlink,
  SiAlchemy,
} as const;

// Type for tech icon names
export type TechIconName = keyof typeof techIconMap;

// Helper function to get an icon component by name
export const getTechIcon = (iconName: TechIconName) => {
  return techIconMap[iconName];
};

// List of all available tech icon names
export const availableTechIcons = Object.keys(techIconMap) as TechIconName[];